# Generated by Django 5.2 on 2025-04-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamer_name', models.CharField(max_length=100)),
                ('game_title', models.CharField(max_length=100)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
